# https://github.com/andrew8088/dotfiles/blob/main/starship/starship.toml
format = """
$directory\
$git_branch\
$git_status\
$git_metrics\
$fill\
$python\
$rlang\
$lua\
$cmd_duration\
$jobs\
$time\
$line_break\
$character"""

# Inserts a blank line between shell prompts
add_newline = false

# Show duration of last command
[cmd_duration]
min_time = 5000
format = "took [$duration](bold yellow)"
disabled = true
show_notifications = false

[directory]
truncation_length = 2
truncate_to_repo = false
disabled = false
read_only = " "

[fill]
symbol = " "

[git_branch]
always_show_remote = false
symbol = " "
# symbol = "\U0001f331 "
# truncation_length = 4
truncation_symbol = ""
# ignore_branches = ["master", "main"]
disabled = false

[git_status]
conflicted = '[=](red)'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
up_to_date = '[✓](bright-green)'
untracked = '[?](bright-red)'
stashed = '$'
modified = '!'
staged = '[++\($count\)](green)'
renamed = '»'
deleted = '[✘](red)'
style = "bright-purple"

[git_metrics]
disabled = false
# added_style = 'bold blue'
# format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[jobs]
symbol = ""
style = "bold red"
number_threshold = 4
format = "[$symbol]($style)"

[python]
symbol = " "
format = "[$symbol$version]($style) "
style = "bold green"
disabled = false

[rlang]
symbol = " "
format = "[$symbol$version]($style) "
style = "bold green"
disabled = false

[lua]
symbol = " "
format = "[$symbol$version]($style) "
style = "bold green"
disabled = false

# Replace the "\u276f" symbol in the prompt with "\u279c"
# [character] # The name of the module we are configuring is "character"
# success_symbol = "[\u279c](bold green)" # The "success_symbol" segment is being set to "\u279c" with the color "bold green"

[time]
disabled = false
format = "[󱑁 $time]($style)"
time_format = '%H:%M'
style = "white"
